import { Video } from './models/video';

export const VIDEOS: Video[] = [
  {
    id: 1,
    filename: 'Star Wars - Episode I – The Phantom Menace.mp4',
    duration: '02:16:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '12MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 2,
    filename: 'Star Wars - Episode II – Attack of the Clones.mp4',
    duration: '02:22:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '15MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 3,
    filename: 'Star Wars - Episode III – Revenge of the Sith.mp4',
    duration: '02:20:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '10MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 4,
    filename: 'Star Wars - Episode IV – A New Hope.mp4',
    duration: '02:05:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '17MB',
    status: 'Processing',
    availableResolutions: ['Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 5,
    filename: 'Star Wars - Episode V – The Empire Strikes Back.mp4',
    duration: '02:07:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '25MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 6,
    filename: 'Star Wars - Episode VI – Return of the Jedi.mp4',
    duration: '02:16:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '32MB',
    status: 'DoneProcessing',
    availableResolutions: ['Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 7,
    filename: 'Star Wars - Episode VII – The Force Awakens.mp4',
    duration: '02:15:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '42MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd1080', 'Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 8,
    filename: 'Star Wars - Episode VIII – The Last Jedi.mp4',
    duration: '02:32:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '52MB',
    status: 'FileUploaded',
    availableResolutions: ['Hd1080', 'Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
  {
    id: 9,
    filename: 'Star Wars - Episode IX – The Rise of Skywalker.mp4',
    duration: '02:22:00',
    bitRate: '48k',
    codecName: 'h264',
    resolution: '4k',
    size: '22MB',
    status: 'ErrorProcessing',
    availableResolutions: ['Hd1080', 'Hd720', 'Hd480'],
    thumbnails: ['1', '2'],
  },
];
